version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=user
    ports:
      - "3306:3306"
    networks:
      - app-network

  springboot:
    image: springboot-test:latest  # 빌드 안했으면 build 옵션 추가 가능
    container_name: springboot-app
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=P@ssw0rd
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

