spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/user
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:P@ssw0rd}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

