name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -f Source/board/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/multicloud-springboot:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/multicloud-springboot:${{ github.sha }}

    - name: Update Deployment manifest
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/multicloud-springboot:${{ github.sha }}|" .
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -am "Update image tag to ${{ github.sha }}"
        git push
